data <- read.table("household_power_consumption.txt", sep = ";", head = T)
library(dplyr)
library(lubridate)
data$Date <- dmy(data$Date)
data$Time <- hms(data$Time)
data <- data %>%
      filter(Date >= ymd("2007-02-01") & Date <= ymd("2007-02-02"))
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
data$DT <- with(data, Date + Time)
data$DT <- ymd_hms(data$DT)
par(mfrow = c(1,1), mar = c(5.1, 4.1, 4.1, 2.1), pty = "s")
png(filename="plot2.png", width = 480, height = 480)
plot(data$DT, data$Global_active_power, type = "l", ylab = "Global Active Power (killowats)", xlab = "")
dev.off()