data <- read.table("household_power_consumption.txt", sep = ";", head = T)
library(dplyr)
library(lubridate)
data$Date <- dmy(data$Date)
data$Time <- hms(data$Time)
data <- data %>%
      filter(Date >= ymd("2007-02-01") & Date <= ymd("2007-02-02"))
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
data$DT <- with(data, Date + Time)
data$DT <- ymd_hms(data$DT)
data$Sub_metering_1 <- as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2 <- as.numeric(as.character(data$Sub_metering_2))
data$Sub_metering_3 <- as.numeric(as.character(data$Sub_metering_3))
par(mfrow = c(1,1), mar = c(5.1, 4.1, 4.1, 2.1), pty = "s")
png(filename="plot3.png", width = 480, height = 480)
plot(data$DT, data$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
points(data$DT, data$Sub_metering_2, type = "l", col = "red")
points(data$DT, data$Sub_metering_3, type = "l", col = "blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty= 1, col=c("black", "red", "blue"), bty = "o")
dev.off()